#
# Create the fabric.
#
#   Because **dcnm_rest** is not idempotent, we can only run this playbook
#   once successfully.  Otherwise, errors will occur.
#
#   Because of Issue #140, we can't use REST API to check for existence of
#   fabric before attempting creation either.
#     https://github.com/CiscoDevNet/ansible-dcnm/issues/140
#
#   Note: Running playbook with "--check" option will still create a fabric.
#

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  collections:
    - cisco.dcnm

  vars:
    # Need to extend timeouts because discovery process is slow
    ansible_command_timeout: 1800
    ansible_connect_timeout: 1800

    switch_username: "{{ lookup('env', 'SWITCH_USER') }}"
    switch_password: "{{ lookup('env', 'SWITCH_PASS') }}"

  tasks:
    # Create the Fabric
    - name: "Create the Classic fabric: '{{ site1.fabric_name }}'"
      # https://galaxy.ansible.com/ui/repo/published/cisco/dcnm/content/module/dcnm_fabric/
      dcnm_fabric:
        state: merged
        config:
        - FABRIC_NAME: "{{ site1.fabric_name }}"
          FABRIC_TYPE: "LAN_CLASSIC"
          BGP_AS: "{{ site1.bgp_as }}"
          IS_READ_ONLY: false
          PM_ENABLE: true
          SNMP_SERVER_HOST_TRAP: true
          ENABLE_NXAPI: true
          ENABLE_NXAPI_HTTP: true
          enableRealTimeBackup: true

