#
# Create Network (L3 and L2) on Aggregate, L2 on Access
#
# Network Engineering First:
#  - Enable SVI feature
#  - Define VLAN and Create SVI
#  - Configure L2 trunk link
# 

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  collections:
    - cisco.dcnm

  vars:
    # Need to extend timeouts because discovery process is slow
    ansible_command_timeout: 1800
    ansible_connect_timeout: 1800

    switch_username: "{{ lookup('env', 'SWITCH_USER') }}"
    switch_password: "{{ lookup('env', 'SWITCH_PASS') }}"

    # WORKSHOP TO-DOs
    vlan_policy_vars:
      NAME: "Red_Five"
      VLAN: 2305
      MODE: "CE"

  tasks:
    # deploy = yes, because interfaces will need them next
    - name: Enable SVI Feature, Create VLAN on Aggregate
      dcnm_policy:
        fabric: "{{ site1.fabric_name }}"
        deploy: yes
        state: merged
        config:
          - name: "feature_interface_vlan_11_1"
            priority: 100
            create_additional_policy: false
          - name: "create_vlan"
            priority: 200
            create_additional_policy: false
            policy_vars: "{{ vlan_policy_vars }}"
          - switch:
            - ip: "{{ site1.spine1_ip }}"

    - name: Create VLAN SVI
      dcnm_interface:
        check_deploy: true
        fabric: "{{ site1.fabric_name }}"
        state: merged
        config:
          - name: "Vlan2305"
            type: svi
            switch:
              - "{{ site1.spine1_ip }}"
            profile:
              mode: vlan
              int_vrf: "default"
              ipv4_addr: "192.168.5.1"
              ipv4_mask_len: 24
              mtu: 1500
              route_tag: 12345
              disable_ip_redirects: true
              enable_hsrp: false
              admin_state: true
              cmds:
              - no shutdown
              - ip route ospf 3155 area 0.0.0.0
            deploy: true

    - name: Create VLAN on Access
      dcnm_policy:
        fabric: "{{ site1.fabric_name }}"
        deploy: yes
        state: merged
        config:
          - name: "create_vlan"
            priority: 200
            create_additional_policy: false
            policy_vars: "{{ vlan_policy_vars }}"
          - switch:
            - ip: "{{ site1.leaf1_ip }}"

    - name: Create L2 Trunk to/from Access
      dcnm_interface:
        fabric: "{{ site1.fabric_name }}"
        check_deploy: yes
        state: merged
        config:
          - name: "Ethernet1/1"
            switch:
              - "{{ site1.spine1_ip }}"
              - "{{ site1.leaf1_ip }}"
            type: eth
            profile:
              admin_state: yes
              bpdu_guard: no
              mode: trunk
              mtu: jumbo
              port_type_fast: yes
              allowed_vlans: "{{ vlan_policy_vars.VLAN }}"

    # Save and Deploy
    - name: Save changes to "{{ site1.fabric_name }}"
      dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ site1.fabric_name }}/config-save"

    - name: Deploy changes to "{{ site1.fabric_name }}"
      dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ site1.fabric_name }}/config-deploy"
